### PR TITLE
Adding custom fields to braintree transaction schema

### PR DESCRIPTION
**Pull request by Ianleeclark**
Hey there, this is in reference to https://github.com/singer-io/tap-braintree/issues/17

I'm not 100% sure if anything else would need to be changed, but I think it should only be a schema change. Anyway, let me know and I'll get anything changed that's needing to be changed.

### CODE REVIEW

**Comment by KAllan357** [comment]
Hi @GrappigPanda, I think this looks reasonable. 

Have you been able to test this locally with the tap? I'm wondering a little bit if it'll work...

Braintree transactions appear to flow out of the API and into the transform module: https://github.com/singer-io/tap-braintree/blob/master/tap_braintree/__init__.py#L124-L129

I suspect after reading that code, that the transform code would recurse until it got to your change where it would get mad about the map with the empty keys here: https://github.com/singer-io/tap-braintree/blob/master/tap_braintree/transform.py#L69.

There's two options if this is true. First is using the transform code in singer-python and replacing this transform code with that. There might be additional implications here. Second would accounting for this error case using code similar to what's in the transformer: https://github.com/singer-io/singer-python/blob/master/singer/transform.py#L135-L137

```
    if "type" not in schema:
        # indicates no typing information so don't bother transforming it
        return True, data

```

**Comment by fernandobrito** [comment]
@Ianleeclark sorry to bother, but I'm also looking into adding `custom fields` on this tap and I wonder why you started this PR but didn't finish it. Was there any technical limitation or special reason why you closed this PR?

**Comment by Ianleeclark** [comment]
@fernandobrito Actually I was doing this for a job, priorities shifted so I never finished it, and then I left the job. I closed it because I never intended to finish it, but, if I recall correctly, there wasn't much to the PR. Sorry that it wasn't kept around

**Comment by fernandobrito** [comment]
@Ianleeclark cool, thanks for taking the time and answering. Then I will test it and open another PR.  🙇 Stay safe!

**Pull request closed without merging**
